export const FEATURES = {
  CREATE_SHOP: 'CREATE_SHOP',
  MAX_STAFF: 'MAX_STAFF',
  MAX_BOOKINGS_PER_MONTH: 'MAX_BOOKINGS_PER_MONTH',
  SMS_REMINDERS: 'SMS_REMINDERS',
  ADVANCED_ANALYTICS: 'ADVANCED_ANALYTICS',
} as const;

export type Feature = keyof typeof FEATURES;
